services:
  backend:
    container_name: apw-go-serv
    image: apw-go
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    depends_on:
      - storage
    ports:
      - "8080:8080"
    environment:
      - SSL_MODE=${SSL_MODE}
      - POSTGRES_URL=${POSTGRES_URL}
    env_file:
      - ../.env-compose

  storage:
    restart: always
    container_name: apw-psql-serv
    image: postgres:16
    env_file:
      - ../.env-compose
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
