services:
  backend:
    container_name: apw-go-serv
    image: apw-go
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    command: /wait.sh /apw
    depends_on:
      - storage
    ports:
      - "8080:8080"
    environment:
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"

      - "SSL_MODE=${SSL_MODE}"
      - "POSTGRES_URL=${POSTGRES_URL}"
    env_file:
      - ../.env-compose

  storage:
    container_name: apw-psql-serv
    image: postgres:16
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - ../sql:/sql
      - ./scripts/create-psql-storage.sh:/docker-entrypoint-initdb.d/create-psql-storage.sh
    restart: always
    env_file:
      - ../.env-compose

volumes:
  storage:
  backend:
